// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFS3cltEk7JUq_RBLAFZl8J8W45aHP8I',
    appId: '1:22181021057:web:78179879d3ca03f8919480',
    messagingSenderId: '22181021057',
    projectId: 'OnParkeytest1',
    authDomain: 'OnParkeytest1.firebaseapp.com',
    storageBucket: 'OnParkeytest1.appspot.com',
    measurementId: 'G-9BM5SYC3G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLwhwC2GU1L_CT69RDwSLEsB8x4EdUz8',
    appId: '1:22181021057:android:3eb18db1751ea72b919480',
    messagingSenderId: '22181021057',
    projectId: 'OnParkeytest1',
    storageBucket: 'OnParkeytest1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgBhMZpUzaThWvaCLFInva-gp0Xy3iP4',
    appId: '1:22181021057:ios:ade577fd366e5b3a919480',
    messagingSenderId: '22181021057',
    projectId: 'OnParkeytest1',
    storageBucket: 'OnParkeytest1.appspot.com',
    iosBundleId: 'com.example.erickcabrera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwgBhMZpUzaThWvaCLFInva-gp0Xy3iP4',
    appId: '1:22181021057:ios:ade577fd366e5b3a919480',
    messagingSenderId: '22181021057',
    projectId: 'OnParkeytest1',
    storageBucket: 'OnParkeytest1.appspot.com',
    iosBundleId: 'com.example.erickcabrera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFS3cltEk7JUq_RBLAFZl8J8W45aHP8I',
    appId: '1:22181021057:web:a19992a6a7913676919480',
    messagingSenderId: '22181021057',
    projectId: 'OnParkeytest1',
    authDomain: 'OnParkeytest1.firebaseapp.com',
    storageBucket: 'OnParkeytest1.appspot.com',
    measurementId: 'G-ESER452XJM',
  );
}
